name: Gauzy Pulumi

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:    
    - name: Pulumi Preview
      env: 
        PULUMI_CI: up
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      uses: docker://pulumi/actions    
      with:
        args: up
