name: Gauzy Pulumi

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: |
        yarn install        
      env:
        CI: true 
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Pulumi Preview
      env: 
        PULUMI_CI: pr
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      uses: docker://pulumi/actions    
      with:
        args: preview
